M48
; DRILL file {KiCad 8.0.3} date 2024-08-08T10:10:10-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-08T10:10:10-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0670
%
G90
G05
T1
X5.249Y-2.3342
X5.249Y-2.6295
T2
X3.4697Y-3.2909
X3.5169Y-2.9563
X4.8083Y-2.9563
X4.8555Y-3.2909
M30
